apiVersion: apps/v1
kind: Deployment
metadata:
  name: bibbi-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bibbi-frontend
  template:
    metadata:
      labels:
        app: bibbi-frontend
    spec:
      containers:
        - name: webserver
          image: no5ing/bibbi-frontend:latest
          resources:
            requests:
              memory: "1.0Gi"
              cpu: "1500m"
            limits:
              memory: "3.0Gi"
              cpu: "1500m"
          ports:
            - containerPort: 3000
