apiVersion: v1
kind: Service
metadata:
  name: bibbi-frontend
  labels:
    app: bibbi-frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: bibbi-frontend
