apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingressroute.yaml
- certificate.yaml
transformers:
- |-
  apiVersion: builtin
  kind: NamespaceTransformer
  metadata:
    name: notImportantHere
    namespace: bibbi-prod
  unsetOnly: true
images:
- name: no5ing/bibbi-frontend
  newName: no5ing/bibbi-frontend
  newTag: f8a24de
