apiVersion: v1
kind: Service
metadata:
  name: bibbi-backend-api
  labels:
    app: bibbi-backend-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: bibbi-backend-api